[tool.pyflow]
name = "koordinaatit"
py_version = "3.8"
version = "0.0.1"
authors = ["Stefan Hagen <stefan@hagen.link>"]

[tool.pyflow.scripts]

[tool.pyflow.dependencies]

[tool.pyflow.dev-dependencies]
